#!/bin/sh
# Pre-bootstrap shared admin credentials for Docker (issue #385).
# Go server and Node.js console must use the same password on first start.
# Writes /opt/rustdesk/.admin_credentials and exports INIT_ADMIN_* / DEFAULT_ADMIN_*.
set -e

CREDS_DIR="${RUSTDESK_PATH:-/opt/rustdesk}"
CREDS_FILE="${CREDS_DIR}/.admin_credentials"
ADMIN_USER="${INIT_ADMIN_USER:-${DEFAULT_ADMIN_USERNAME:-${ADMIN_USERNAME:-admin}}}"

# Map public ADMIN_* aliases to internal seed vars (same as entrypoints).
if [ -n "${ADMIN_USERNAME:-}" ] && [ -z "${INIT_ADMIN_USER:-}" ]; then
    export INIT_ADMIN_USER="$ADMIN_USERNAME"
fi
if [ -n "${ADMIN_USERNAME:-}" ] && [ -z "${DEFAULT_ADMIN_USERNAME:-}" ]; then
    export DEFAULT_ADMIN_USERNAME="$ADMIN_USERNAME"
fi
if [ -n "${ADMIN_PASSWORD:-}" ] && [ -z "${INIT_ADMIN_PASS:-}" ]; then
    export INIT_ADMIN_PASS="$ADMIN_PASSWORD"
fi
if [ -n "${ADMIN_PASSWORD:-}" ] && [ -z "${DEFAULT_ADMIN_PASSWORD:-}" ]; then
    export DEFAULT_ADMIN_PASSWORD="$ADMIN_PASSWORD"
fi

ADMIN_USER="${INIT_ADMIN_USER:-${DEFAULT_ADMIN_USERNAME:-admin}}"

sync_exports() {
    export INIT_ADMIN_USER="${INIT_ADMIN_USER:-$ADMIN_USER}"
    export DEFAULT_ADMIN_USERNAME="${DEFAULT_ADMIN_USERNAME:-$ADMIN_USER}"
    if [ -n "${INIT_ADMIN_PASS:-}" ]; then
        export DEFAULT_ADMIN_PASSWORD="${DEFAULT_ADMIN_PASSWORD:-$INIT_ADMIN_PASS}"
    elif [ -n "${DEFAULT_ADMIN_PASSWORD:-}" ]; then
        export INIT_ADMIN_PASS="${INIT_ADMIN_PASS:-$DEFAULT_ADMIN_PASSWORD}"
    fi
}

parse_creds_password() {
    _file="$1"
    if [ ! -f "$_file" ] || [ ! -r "$_file" ]; then
        return 1
    fi
    _pass=$(grep -m1 '^Admin Password:' "$_file" 2>/dev/null | sed 's/^Admin Password:[[:space:]]*//')
    if [ -n "$_pass" ]; then
        printf '%s\n' "$_pass"
        return 0
    fi
    return 1
}

write_as_betterdesk() {
    _path="$1"
    _content="$2"
    if command -v su-exec >/dev/null 2>&1; then
        printf '%s' "$_content" | su-exec betterdesk sh -c "umask 077; cat > \"$_path\""
    else
        printf '%s' "$_content" | su -s /bin/sh betterdesk -c "umask 077; cat > \"$_path\""
    fi
}

# Already configured via env — keep Go and Node in sync.
if [ -n "${INIT_ADMIN_PASS:-}" ] || [ -n "${DEFAULT_ADMIN_PASSWORD:-}" ]; then
    sync_exports
    return 0 2>/dev/null || exit 0
fi

# Reuse existing credentials file on shared volume.
_existing_pass=$(parse_creds_password "$CREDS_FILE" || true)
if [ -z "$_existing_pass" ]; then
    _existing_pass=$(parse_creds_password "${DATA_DIR:-/app/data}/.admin_credentials" || true)
fi
if [ -n "$_existing_pass" ]; then
    export INIT_ADMIN_PASS="$_existing_pass"
    export DEFAULT_ADMIN_PASSWORD="$_existing_pass"
    sync_exports
    return 0 2>/dev/null || exit 0
fi

# Fresh install: generate once before either service starts.
mkdir -p "$CREDS_DIR" 2>/dev/null || true
if command -v openssl >/dev/null 2>&1; then
    _new_pass=$(openssl rand -hex 16)
else
    _new_pass=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
fi

_creds_content="Admin Username: ${ADMIN_USER}
Admin Password: ${_new_pass}
Generated by: BetterDesk Docker bootstrap
Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
"

if [ "$(id -u)" = "0" ]; then
    write_as_betterdesk "$CREDS_FILE" "$_creds_content"
else
    umask 077
    printf '%s' "$_creds_content" > "$CREDS_FILE"
fi

export INIT_ADMIN_PASS="$_new_pass"
export DEFAULT_ADMIN_PASSWORD="$_new_pass"
sync_exports

echo "Bootstrap admin credentials → ${CREDS_FILE}"
